FIREFOX_DEBUG_OBJ   = /run/media/lixing/20170318_4TB/src/browser/firefox/firefox-52.0.2/objdir-droid/
FIREFOX_RELEASE_OBJ = /run/media/lixing/20170318_4TB/src/browser/firefox/firefox-52.0.2/objdir-droid/

FIREFOX_DEBUG_DIST   = $(FIREFOX_DEBUG_OBJ)dist/
FIREFOX_RELEASE_DIST = $(FIREFOX_RELEASE_OBJ)dist/

RELEASE =1
BITS = 64

MYLDFLAGS = -Wl,-rpath=.:./lib64  -Wl,-Bstatic  -lc -lm -lrt -L/home/lixing/lib64 -lstdc++ -lsupc++  -Wl,-Bdynamic 

CFS =  -D__LINUX__ -DXP_UNIX -DMOZ_HAVE_CXX11_FINAL -static 
ifeq ($(RELEASE), 0)
CFS += -g
MOZ_ROOT = $(FIREFOX_DEBUG_DIST)
else
CFS +=  -DNDEBUG
MOZ_ROOT = $(FIREFOX_RELEASE_DIST)
endif

ifeq ($(BITS),32)
CFS += -m32
else
CFS += -m64
endif

OBJ_PATH = obj/



$(OBJ_PATH)%.o:%.cxx
	@echo "*** Compile cxx $<..."
	@echo $(OBJFILES)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJ_PATH)%.o:%.c
	@echo "*** Compile c $<..."
	@echo $(SRC)
	$(CXX) $(CXXFLAGS) -c $< -o $@
